### ISSUE TITLE
Scapy is not working when IP is used as range in the ARP packet

### ISSUE THREAD

**Issue by Parveshdhull** [secdev/scapy#2400]
Python Version: **3.8.1 & 2.7.17**(Tried Both)

Scapy Version: **2.4.3**

**Where Working?**

It is working fine with a single IP address.
![DeepinScreenshot_select-area_20200104155528](https://user-images.githubusercontent.com/17097240/71767294-e3806680-2f30-11ea-85fa-672b621fa605.png)

**Where Not Working?**

When passing the IP range in the constructor, it never worked.

But when we assign IP range, it works sometimes.

![DeepinScreenshot_select-area_20200104161917](https://user-images.githubusercontent.com/17097240/71767302-0579e900-2f31-11ea-9176-1b8e7ec211d1.png)

**Tried Methods?**

Tried in the script, like

```
from scapy.all import ARP
arp_request = ARP()
arp_request.pdst = ip
print(arp_request.summary())
```

Tried in terminal using scapy, whose screenshot attached above

**EDIT:** I tried to analyze packets sent by the main device using Wireshark on one of the devices present in the network.

I find that in spite of showing range as ??, sometime ARP request covers whole range 0-256 and programs stop successfully. But sometimes it stops at 192.168.43.170 and keeps sending the request for 192.168.43.1. And this also blocks the internet.

I don't know why at 192.168.43.170 because my gateway is at 192.168.43.1 and devices are at 192.168.43.98 and 192.168.43.198

**Wireshark Output**
![DeepinScreenshot_select-area_20200104232928](https://user-images.githubusercontent.com/17097240/71769825-bc835e00-2f4b-11ea-8028-b7f69003d25f.png)

**Comment by gpotter2** [comment]
Did you retry against master ?
I'm pretty sure this was fixed in https://github.com/secdev/scapy/pull/2395

**Comment by Parveshdhull** [comment]
Thanks, @gpotter2 

I tried master and range representation, in summary, shows right.
But the problem persists. 
I created a broadcast arp packet and broadcasted it. First time it completed the whole subnet and return 2 results. But second time it again got stuck on 170.
And it kept sending requests and blocked network.
I stopped using KeyboardInterrupt, and it printed some errors, displayed in Image.
**SCAPY**
![DeepinScreenshot_select-area_20200105192451](https://user-images.githubusercontent.com/17097240/71781226-3110d800-2ff2-11ea-802b-35ca7658eb90.png)

**WireShark**
![DeepinScreenshot_select-area_20200105192541](https://user-images.githubusercontent.com/17097240/71781234-41c14e00-2ff2-11ea-864a-1247c0bc109a.png)

**Comment by Parveshdhull** [comment]
These all above screenshots are from arch linux, I tried in debian based os and it worked fine. I think there was something wrong with my system, not with scapy.

**Comment by hackerish1** [comment]
even i have same issue. can anyone tell me how to fix this

**Comment by ibrahimmalek** [comment]
am facing the same with Kali Linux if  creating ARP request with a single IP it works fine but with a range its getting me ?????
please advice

**Comment by GuyMan1020** [comment]
I just downgraded my scapy by doing:

sudo pip install scapy==2.4.2 --upgrade 

and it ended up working

**Comment by nikhildr22** [comment]
upgrading scapy to its latest version will solve the issue - [stackoverflow](https://stackoverflow.com/a/64166478/10841074 )
