### ISSUE TITLE
NTP Authenticator parsing broken for SHA MAC

### ISSUE THREAD

**Issue by Olegandr** [secdev/scapy#2731]
#### Brief description

Parsing of NTP packet Authenticator, that uses SHA-based MAC, incorrectly identifies key id and message digest.

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.8
-   Operating System: Ubuntu/Windows

#### How to reproduce

Use NTP packet capture with NTP Version 4 packets using SHA1, SHA256, SHA512 message authentication (produced by chrony or ntpd NTP server.)
Use show() command to parse packet.

#### Actual result

###[ UDP ]###
        sport     = 42270
        dport     = ntp
        len       = 80
        chksum    = 0x731a
###[ NTPHeader ]###
           leap      = no warning
           version   = 4
           mode      = client
           stratum   = 0
           poll      = 7
           precision = 32
           delay     = 0.0
           dispersion= 0.0
           ref_id    = b''
           ref       = 0.0
           orig      = 0.0
           recv      = 0.0
           sent      = 1388821533.8530993
###[ NTPv4 extensions ]###
              \extensions\
               |###[ Raw ]###
               |  load      = '\x00\x00\x00\x0b'
              \mac       \
               |###[ Authenticator ]###
               |  padding   = None
               |  key_id    = 3452142173
               |  dgst      = bf6b7ad02886ff45aa8b2eaf7ac78bc1

#### Expected result
Key ID should be 0x0000000b (11)
Digest should be 
cdc3825dbf6b7ad02886ff45aa8b2eaf7ac78bc1
This also corresponds with RFC description, Wireshark output, performed server setup, actual message digest if calculated based on RFC.

#### Related resources
Hex stream of example packets for easier import:
1. client
000c2962f268d094666d23750800450000640db640004011a519c0a80364c0a80305a51e007b0050731a2300072000000000000000000000000000000000000000000000000000000000000000000000000052c7bc1dda64b97d0000000bcdc3825dbf6b7ad02886ff45aa8b2eaf7ac78bc1
2. server
d094666d2375000c29a9635908004500006428ab400040118a27c0a80302c0a80364007ba51e00508818240407e70000000700000002c0a80301e2c27398f95cc96a52c7bc1dda64b97de2c273a7eb366588e2c273a7eb391be50000000b9a6178d82b4408adfd9cab87f04ad1c92b280171

**Comment by guedou** [comment]
Thanks for reporting the issue. The problem occurs in https://github.com/secdev/scapy/blob/master/scapy/layers/ntp.py#L449

Here is howto decode the packet correctly by forcing the usage of NTPAuthenticator:
```
>>> packet = Ether(hex_bytes("000c2962f268d094666d23750800450000640db640004011a519c0a80364c0a80305a51e007b
...:0050731a2300072000000000000000000000000000000000000000000000000000000000000000000000000052c7bc1dda64b9
...:7d0000000bcdc3825dbf6b7ad02886ff45aa8b2eaf7ac78bc1"))
>>> packet[NTPHeader].decode_payload_as(NTPAuthenticator)
>>> packet[NTPHeader]
<NTPHeader  leap=no warning version=4 mode=client stratum=0 poll=7 precision=32 delay=0.0 dispersion=0.0 ref_id=b'' ref=0.0 orig=0.0 recv=0.0 sent=1388821533.8530993 |<NTPAuthenticator  padding='\x00\x00\x00\x0b' key_id=3452142173 dgst=bf6b7ad02886ff45aa8b2eaf7ac78bc1 |>>
```

**Comment by Olegandr** [comment]
Thank you, scapy documentation leaves a LOT for guesswork.
There were not a single example that i was able to make work without modifying based on guessing.
You example offers a lot of ways to do things that are new for me. -)

**Comment by guedou** [comment]
Feel free to contribute to the documentation. The fix is available in #2732

**Comment by Olegandr** [comment]
Still does not seem to work in 2.4.4.
```
###[ UDP ]###
        sport= ntp
        dport= ntp
        len= 80
        chksum= 0xdb3b
###[ NTPHeader ]###
           leap= unknown (clock unsynchronized)
           version= 4
           mode= client
           stratum= 0
           poll= 6
           precision= 232
           delay= 0.0
           dispersion= 0.0
           ref_id= b'INIT'
           ref= 0.0
           orig= 0.0
           recv= 0.0
           sent= Tue, 02 Jun 2020 23:37:12 +0000
###[ Authenticator ]###
              padding= '\x00\x00\x00\x0c'
              key_id= 3523582088
              dgst= b4a2adc11d2dbd1420a43560bf92c6f9
```
In the exmple above 0c should be the key id and the remaining should be a MAC code.
