### ISSUE TITLE
Scapy route6 configuration

### ISSUE THREAD

**Issue by pegom96** [secdev/scapy#546]
I'm using scapy to build some IPv6 packets. I'm having trouble in the communications between hosts on the same network and with external links as well, I'm only able to communicate with my router. For example if I make a router solicitation request it works fine, but if I make a ICMPv6EchoRequest to the ff02::1(all nodes on the network) I only get an answer from the router and not the other connected hosts. If I use the ping6 command I can perfectly ping all the hosts on my network and external links as well, which leads me to think that it is a problem with scapy. 

My conf.iface6 is on the right interface, butmy route6 is empty(my route from IPv4 is not) even if I add a new route6 conf.route6.add(myip6, gw ='router ipv6', dev='interface') my route6 continues to be empty. My conf.route6.routes are not empty and I think they are well configured. I really don't see where's the problem, plus everything is working fine with the OS(which is Linux) IPv6 configurations .

**Comment by gpotter2** [comment]
I was able to replicate with
`sr1(IPv6(dst="ff02::1")/ICMPv6EchoRequest())`

The IPv6 packet is sent, and the reply are recieved (shown by wireshark); but scapy does not detect them.

**Comment by pegom96** [comment]
I'll check it my self, but why does scapy do not detect the packets ?

**Comment by gpotter2** [comment]
Sounds like a bug

**Comment by pegom96** [comment]
Just used the sniff function to check for ICMPv6EchoReply packets , and I receive them fine. 

How are we supposed to report the bug ?

**Comment by gpotter2** [comment]
I've found the bug, that's because the answers look like
```
<Ether  dst=d0:50:99:56:dd:f9 src=c4:6e:1f:41:d1:d1 type=0x86dd |<IPv6  version=6L tc=0L fl=0L plen=8 nh=ICMPv6 hlim=64 src=fe80::c66e:1fff:fe41:d1d1 dst=fe80::dc1d:24e8:af00:125e |<ICMPv6EchoReply  type=Echo Reply code=0 cksum=0x8d5 id=0x0 seq=0x0 |>>>
```
So whereas https://github.com/secdev/scapy/blob/master/scapy/layers/inet6.py#L1323 should return
'\x00\x00\x00\x00'
it's also using Ether() which is not wanted.

I PR a fix soon

**Comment by pegom96** [comment]
Perfect. Is there a way we can know the announcement of the bug fix ?

**Comment by gpotter2** [comment]
Ok [that](https://github.com/secdev/scapy/issues/547) should fix it

**Comment by pegom96** [comment]
It did not fix it for me, but I think that the problem is not on the bug fix which should work. I have a different inet6.py file from the bug fixed one , i have 3077 lines of code and the bug fixed one has around 3700 lines. I have the last version of scapy. When I overwrite my inet6.py file to the one of the bug fixed I got importation warnings and I don't see exactly why. 

**Warnings :** 
"""
WARNING: can't import layer inet: invalid syntax (inet6.py, line 172)
WARNING: can't import layer dhcp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer dns: invalid syntax (inet6.py, line 172)
WARNING: can't import layer gprs: invalid syntax (inet6.py, line 172)
WARNING: can't import layer hsrp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer inet6: invalid syntax (inet6.py, line 172)
WARNING: can't import layer isakmp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer l2tp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer mgcp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer mobileip: invalid syntax (inet6.py, line 172)
WARNING: can't import layer netbios: invalid syntax (inet6.py, line 172)
WARNING: can't import layer ntp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer ppp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer rip: invalid syntax (inet6.py, line 172)
WARNING: can't import layer sebek: invalid syntax (inet6.py, line 172)
WARNING: can't import layer skinny: invalid syntax (inet6.py, line 172)
WARNING: can't import layer smb: invalid syntax (inet6.py, line 172)
WARNING: can't import layer snmp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer tftp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer dhcp6: invalid syntax (inet6.py, line 172)
WARNING: can't import layer llmnr: invalid syntax (inet6.py, line 172)
WARNING: can't import layer sctp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer vrrp: invalid syntax (inet6.py, line 172)
WARNING: can't import layer ipsec: invalid syntax (inet6.py, line 172)
"""

**Comment by gpotter2** [comment]
Make sure you are using the latest Dev version
(Download the zip of master then:
`python setup.py install`)

**Comment by pegom96** [comment]
I downloaded the ZIP of the master folder, I'm trying to run setup.py with python, but I use python3.5 because of that I'm getting an error : 

**Error :** 
sudo: unable to resolve host alyattes_lion
  File "setup.py", line 36
    os.chmod(fname, 0755)
                       ^
SyntaxError: invalid token

Is there a way to install the scapy of master  in python3.5 =

**Comment by gpotter2** [comment]
Oh...
Scapy is not compatible yet with python 3.*
Please use python 2.7*

Sorry :/

**Comment by pegom96** [comment]
I actually have a version of scapy installed on python3.* I only noticed now that the creators also have a github page, I thought only one github page existed for scapy. 

Anyway thank you so much for your help gpotter2, seriously. !

**Comment by gpotter2** [comment]
No problem,

You are using a fork called ˋscapy3k ` of this (the original) version of scapy.
