### ISSUE TITLE
TLS ServerHello error : type object has no attribute 'kx_alg'

### ISSUE THREAD

**Issue by chifflier** [secdev/scapy#959]
Note: I'm using scapy git version fb8068c3d19fb6c5a2fbfdb339dc45d78a04ef54

When using python 2.7 to create TLS ServerHello messages (without state), the following code
```python
from scapy.all import *
from scapy.layers.tls.record import *
from scapy.layers.tls.handshake import *

print str(TLS(msg=TLSServerHello(cipher=0xc02f)))
```

fails with the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/packet.py", line 336, in __str__
    return str(self.build())
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/packet.py", line 436, in build
    p = self.do_build()
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/packet.py", line 418, in do_build
    pkt = self.self_build()
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/packet.py", line 399, in self_build
    p = f.addfield(self, p, val)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/layers/tls/record.py", line 183, in addfield
    res += self.i2m(pkt, p)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/layers/tls/record.py", line 168, in i2m
    p.post_build_tls_session_update(cur)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/layers/tls/session.py", line 847, in post_build_tls_session_update
    self.tls_session_update(msg_str)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/layers/tls/handshake.py", line 387, in tls_session_update
    tls_version=self.version)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/layers/tls/session.py", line 283, in __init__
    connState.__init__(self, read_or_write="write", **kargs)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/layers/tls/session.py", line 89, in __init__
    self.key_exchange = ciphersuite.kx_alg()
AttributeError: type object 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256' has no attribute 'kx_alg'
```

Note: installing the `cryptography` module apparently solves the problem.

**Comment by guedou** [comment]
Thanks for reporting this issue!

Fun fact, using `raw()` instead of `str()` works fine. @p-l- @gpotter2 you might want to investigate.

I manage to easily fix this issue, but I need to have a closer look to propose a definitive PR.

**Comment by chifflier** [comment]
Using `raw` (without `cryptography`) in the oneliner seems to work, but not in the full example using `wrpcap`.
The same error is triggered in `raw`, here is the top of the backtrace:
```
Traceback (most recent call last):
  File "./flow-test-01.py", line 51, in <module>
    wrpcap('flow-test-01.pcap', flow)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/utils.py", line 688, in wrpcap
    fdesc.write(pkt)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/utils.py", line 1111, in write
    self._write_packet(p)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/utils.py", line 1170, in _write_packet
    s = raw(packet)
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/compat.py", line 66, in raw
    return x.__bytes__()
  File "/home/pollux/LOCAL/TLS/venv-scapy/local/lib/python2.7/site-packages/scapy/packet.py", line 338, in __bytes__
    return self.build()
...
AttributeError: type object 'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA' has no attribute 'kx_alg'
```

**Comment by gpotter2** [comment]
Fixed by https://github.com/secdev/scapy/pull/962

**Comment by guedou** [comment]
The patch seems incomplete has it does not fix the AttributError.

**Comment by chifflier** [comment]
Have you tested with or without the `cryptography` module ? After a pull + install, the error is still present here (without).

**Comment by gpotter2** [comment]
Cannot reproduce :/

![image](https://user-images.githubusercontent.com/10530980/33284724-4c794a78-d3b0-11e7-9541-efb3af3518bf.png)

**Comment by chifflier** [comment]
OK, so the problem is now triggered when creating the TLS ServerHello on top of IP/TCP.
Oneliner triggering the error:
```shell
python2.7 -c 'from scapy.all import *;
from scapy.layers.tls.record import *;
from scapy.layers.tls.handshake import *;
sh = IP()/TCP()/TLS(msg=TLSServerHello(cipher=0xc02f)); wrpcap("/tmp/out.pcap",sh)'
```

Adding the real IP/TCP parameters (src,dst,etc.) does not change anything.
If you remove the `IP()/TCP()/` part, the example works fine.

**Comment by gpotter2** [comment]
What makes no sense is that you are trying to create a TLS layer without using any TLS encryption as you have not installed the encryption library.

Anyway, this should be fixed on the #966 PR :)
